name: Build & Deploy Splash Docker

permissions:
  contents: read
  packages: write # Needed for GHCR

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - docker-setup # Optional automatic trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ghcr.io/the-jade-platform/splash-page:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/the-jade-platform/splash-page:latest .

      - name: Push Docker image
        run: docker push ghcr.io/the-jade-platform/splash-page:latest

  deploy:
    needs: build-and-push # Wait for build-and-push to finish
    if: ${{ success() }} # Only run if the previous job succeeded
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Log in to GHCR using org token
            echo "${{ secrets.HOPES_ORG_TOKEN }}" | docker login ghcr.io -u the-jade-platform --password-stdin

            # Pull the latest image and restart container
            docker pull ghcr.io/the-jade-platform/splash-page:latest
            docker stop splash-page || true
            docker rm splash-page || true
            docker run -d --name splash-page -p 80:80 ghcr.io/the-jade-platform/splash-page:latest
