name: Deploy Splash Container to EC2

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Build & Push Splash Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Log in to GHCR using org token
            echo "${{ secrets.HOPES_ORG_TOKEN }}" | docker login ghcr.io -u the-jade-platform --password-stdin

            # Pull the latest image and restart container
            docker pull ghcr.io/the-jade-platform/splash-page:latest
            docker stop splash-page || true
            docker rm splash-page || true
            docker run -d --name splash-page -p 80:80 ghcr.io/the-jade-platform/splash-page:latest
